// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB43rZUHdJxAbi41XYq3g82q2Nu26AzIQs',
    appId: '1:320004465418:web:737c2633fef09eb06810f3',
    messagingSenderId: '320004465418',
    projectId: 'smartshoppinglist-75c93',
    authDomain: 'smartshoppinglist-75c93.firebaseapp.com',
    storageBucket: 'smartshoppinglist-75c93.appspot.com',
    measurementId: 'G-9CB4BJY6F9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcVpxvgEfIHD55Xc3TAdmG5rkamuywjdE',
    appId: '1:320004465418:android:a379823b6e0331b06810f3',
    messagingSenderId: '320004465418',
    projectId: 'smartshoppinglist-75c93',
    storageBucket: 'smartshoppinglist-75c93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjzoIsUDSzQsAo6qf5CDVdKLsY0-uP5J0',
    appId: '1:320004465418:ios:e51868382d192a306810f3',
    messagingSenderId: '320004465418',
    projectId: 'smartshoppinglist-75c93',
    storageBucket: 'smartshoppinglist-75c93.appspot.com',
    iosBundleId: 'com.example.smartShoppingList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjzoIsUDSzQsAo6qf5CDVdKLsY0-uP5J0',
    appId: '1:320004465418:ios:e51868382d192a306810f3',
    messagingSenderId: '320004465418',
    projectId: 'smartshoppinglist-75c93',
    storageBucket: 'smartshoppinglist-75c93.appspot.com',
    iosBundleId: 'com.example.smartShoppingList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB43rZUHdJxAbi41XYq3g82q2Nu26AzIQs',
    appId: '1:320004465418:web:1c5484664afb2c766810f3',
    messagingSenderId: '320004465418',
    projectId: 'smartshoppinglist-75c93',
    authDomain: 'smartshoppinglist-75c93.firebaseapp.com',
    storageBucket: 'smartshoppinglist-75c93.appspot.com',
    measurementId: 'G-TLSQQT6N18',
  );
}
